#!/usr/bin/env python3
"""Build or verify the deterministic compact durable-record index."""

from __future__ import annotations

import argparse
import re
import stat
from dataclasses import dataclass
from pathlib import Path

from generated_evidence_io import write_regular_repository_file

ROOT = Path(__file__).resolve().parents[1]
RECORD_ROOT = ROOT / "records"
OUTPUT = RECORD_ROOT / "INDEX.md"
MAX_RECORD_BYTES = 64 * 1024

TYPE_RULES = (
    ("Decision", "decisions", re.compile(r"D-[0-9]{3}")),
    ("Task", "tasks", re.compile(r"RIT-[0-9]{3}")),
    ("Incident", "incidents", re.compile(r"INC-[0-9]{3}")),
    ("Experiment", "experiments", re.compile(r"EXP-[0-9]{3}")),
)


@dataclass(frozen=True)
class Record:
    kind: str
    record_id: str
    title: str
    path: str


def _regular_repository_file(path: Path) -> None:
    try:
        mode = path.lstat().st_mode
    except FileNotFoundError as exc:
        raise ValueError(f"record file disappeared: {path.relative_to(ROOT)}") from exc
    if stat.S_ISLNK(mode) or not stat.S_ISREG(mode):
        raise ValueError(f"record inputs must be regular non-symlink files: {path.relative_to(ROOT)}")
    try:
        path.resolve(strict=True).relative_to(ROOT.resolve(strict=True))
    except ValueError as exc:
        raise ValueError(f"record path escapes repository: {path}") from exc
    if path.stat().st_size > MAX_RECORD_BYTES:
        raise ValueError(f"record exceeds {MAX_RECORD_BYTES} bytes: {path.relative_to(ROOT)}")


def records() -> tuple[Record, ...]:
    found: list[Record] = []
    seen: set[str] = set()
    for kind, directory, id_pattern in TYPE_RULES:
        base = RECORD_ROOT / directory
        if not base.exists():
            continue
        if not base.is_dir() or base.is_symlink():
            raise ValueError(f"record directory is unsafe: records/{directory}")
        for path in sorted(base.iterdir(), key=lambda item: item.name):
            _regular_repository_file(path)
            match = re.fullmatch(rf"({id_pattern.pattern})\.md", path.name)
            if match is None:
                raise ValueError(f"unexpected record filename: {path.relative_to(ROOT)}")
            record_id = match.group(1)
            if record_id in seen:
                raise ValueError(f"duplicate record ID: {record_id}")
            seen.add(record_id)
            try:
                first_line = path.read_text(encoding="utf-8").splitlines()[0]
            except (UnicodeDecodeError, IndexError) as exc:
                raise ValueError(f"record is empty or not UTF-8: {path.relative_to(ROOT)}") from exc
            heading = re.fullmatch(rf"# {re.escape(record_id)}: (.+)", first_line)
            if heading is None or not heading.group(1).strip():
                raise ValueError(f"record heading must match filename ID: {path.relative_to(ROOT)}")
            title = heading.group(1).strip()
            if "|" in title or "\n" in title or "\r" in title:
                raise ValueError(f"record title contains an unsafe table delimiter: {path.relative_to(ROOT)}")
            found.append(Record(kind, record_id, title, path.relative_to(ROOT).as_posix()))
    return tuple(sorted(found, key=lambda item: (item.kind, item.record_id, item.path)))


def render_index() -> str:
    lines = [
        "# Durable record index",
        "",
        "> Generated by `scripts/build_record_index.py`; do not edit by hand.",
        "",
        "| Type | ID | Title | Record |",
        "| --- | --- | --- | --- |",
    ]
    for item in records():
        target = item.path.removeprefix("records/")
        lines.append(f"| {item.kind} | {item.record_id} | {item.title} | [{target}](./{target}) |")
    lines.extend(["", "The index is discovery metadata only; canonical state and approvals remain in their named sources.", ""])
    return "\n".join(lines)


def write_index() -> None:
    write_regular_repository_file(ROOT, OUTPUT, render_index())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed index is stale")
    args = parser.parse_args()
    try:
        rendered = render_index()
    except ValueError as exc:
        print(f"Record index validation failed: {exc}")
        return 1
    if args.check:
        if OUTPUT.is_symlink() or not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print("Record index is stale; run: python3 scripts/sync_generated_evidence.py")
            return 1
        print(f"Record index is current ({len(records())} records)")
        return 0
    if OUTPUT.exists() and (OUTPUT.is_symlink() or not stat.S_ISREG(OUTPUT.lstat().st_mode)):
        print("Record index output must be a regular non-symlink file")
        return 1
    write_index()
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(records())} records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
